// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tsvtgoljjzctgdbvvojm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRzdnRnb2xqanpjdGdkYnZ2b2ptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxNTk0NjEsImV4cCI6MjA2MzczNTQ2MX0.Kjw9GJfYP_GbK1PB6ryZg-3WGK3MpHqJvJByKoGakl8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);